services:
  metastore:
    image: postgres:11
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  master:
    image: bigdata-master
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
      - "10000:10000"
    volumes:
      - namenode:/opt/hadoop/dfs/name
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker1:
    image: bigdata-worker
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker2:
    image: bigdata-worker
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "history:172.28.1.5"

  history:
    image: bigdata-history
    hostname: history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: history
    ports:
      - "18080:18080"
      - "19888:19888"
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.5
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"

  jupyter:
    image: bigdata-jupyter
    hostname: jupyter
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.6
      SPARK_LOCAL_HOSTNAME: jupyter
    depends_on:
      - master
      - worker1
      - worker2
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/home/jupyter
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.6
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  dev:
    image: bigdata-dev
    hostname: dev
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.7
      SPARK_LOCAL_HOSTNAME: dev
    volumes:
      - ./dev/home:/home/jupyter
    networks:
      sparknet:
        ipv4_address: 172.28.1.20
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # ######################  zookeeper-1 ##########################
  # zookeeper-1:
  #   image: bigdata-zookeeper
  #   hostname: zookeeper-1
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: yes
  #     ZOOKEEPER_SERVER_ID: 1
  #   ports:
  #     - 2181:2181 #client connections
  #     - 2788:2788 #follower connections
  #     - 3788:3788 #leader election
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: always
  #   networks:
  #     sparknet:
  #       ipv4_address: 172.28.1.7
  #   extra_hosts:
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "worker2:172.28.1.4"
  #     - "history:172.28.1.5"
  #     - "zookeeper-2:172.28.1.8"
  #     - "zookeeper-3:172.28.1.9"
      
  # ######################  zookeeper-2 ##########################
  # zookeeper-2:
  #   image: bigdata-zookeeper
  #   hostname: zookeeper-2
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: yes
  #     ZOOKEEPER_SERVER_ID: 2
  #   ports:
  #     - 2281:2181 #client connections
  #     - 2888:2788 #follower connections
  #     - 3888:3788 #leader election
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: always
  #   networks:
  #     sparknet:
  #       ipv4_address: 172.28.1.8
  #   extra_hosts:
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "worker2:172.28.1.4"
  #     - "history:172.28.1.5"
  #     - "zookeeper-1:172.28.1.7"
  #     - "zookeeper-3:172.28.1.9"

  # ######################  zookeeper-3 ##########################
  # zookeeper-3:
  #   image: bigdata-zookeeper
  #   hostname: zookeeper-3
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: yes
  #     ZOOKEEPER_SERVER_ID: 3
  #   ports:
  #     - 2381:2181 #client connections
  #     - 2988:2788 #follower connections
  #     - 3988:3788 #leader election
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro # set timezone of docker container equal to host timezone
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: always
  #   networks:
  #     sparknet:
  #       ipv4_address: 172.28.1.9
  #   extra_hosts:
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "worker2:172.28.1.4"
  #     - "history:172.28.1.5"
  #     - "zookeeper-1:172.28.1.7"
  #     - "zookeeper-2:172.28.1.8"



  kafka-gen:
    image: bigdata-kafka
    hostname: kafka-gen
    container_name: kafka-gen
    volumes:
      - ./kafka/scripts/create_cluster_id.sh:/tmp/create_cluster_id.sh
      - ./kafka/clusterID:/tmp/clusterID
    command: "bash -c '/tmp/create_cluster_id.sh'"

 ######################  kafka-broker-1 ##########################
  kafka-broker-1:
    image: bigdata-kafka
    hostname: kafka1
    container_name: kafka1
    ports:
      - "39092:39092"
    environment:
      KAFKA_LISTENERS: BROKER://kafka1:19092,EXTERNAL://kafka1:39092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:19092,EXTERNAL://kafka1:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_HOURS: 168
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka1-data:/var/lib/kafka/data
      - ./kafka/clusterID:/tmp/clusterID
    networks:
      sparknet:
        ipv4_address: 172.28.1.10
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "zookeeper-1:172.28.1.7"
      - "zookeeper-2:172.28.1.8"
      - "zookeeper-3:172.28.1.9"
      - "kafka1:172.28.1.10"
      - "kafka2:172.28.1.11"
      - "kafka3:172.28.1.12"

######################  kafka-broker-2 ##########################
  kafka-broker-2:
    image: bigdata-kafka
    hostname: kafka2
    container_name: kafka2
    ports:
      - "39093:39093"
    environment:
      KAFKA_LISTENERS: BROKER://kafka2:19093,EXTERNAL://kafka2:39093,CONTROLLER://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:19093,EXTERNAL://kafka2:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_LOG_SEGMENT_HOURS: 168
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka1-data:/var/lib/kafka/data
      - ./kafka/clusterID:/tmp/clusterID
    networks:
      sparknet:
        ipv4_address: 172.28.1.11
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "zookeeper-1:172.28.1.7"
      - "zookeeper-2:172.28.1.8"
      - "zookeeper-3:172.28.1.9"
      - "kafka1:172.28.1.10"
      - "kafka2:172.28.1.11"
      - "kafka3:172.28.1.12"


######################  kafka-broker-3 ##########################
  kafka-broker-3:
    image: bigdata-kafka
    hostname: kafka3
    container_name: kafka3
    ports:
      - "39094:39094"
    environment:
      KAFKA_LISTENERS: BROKER://kafka3:19094,EXTERNAL://kafka3:39094,CONTROLLER://kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:19094,EXTERNAL://kafka3:39094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_LOG_SEGMENT_HOURS: 168
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka1-data:/var/lib/kafka/data
      - ./kafka/clusterID:/tmp/clusterID
    networks:
      sparknet:
        ipv4_address: 172.28.1.12
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "zookeeper-1:172.28.1.7"
      - "zookeeper-2:172.28.1.8"
      - "zookeeper-3:172.28.1.9"
      - "kafka1:172.28.1.10"
      - "kafka2:172.28.1.11"
      - "kafka3:172.28.1.12"

  my-kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: my-kafka-ui
      ports:
        - "7070:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19092,kafka2:19093,kafka3:19094
      networks:
        sparknet:
          ipv4_address: 172.28.1.13
      extra_hosts:
        - "kafka1:172.28.1.10"
        - "kafka2:172.28.1.11"
        - "kafka3:172.28.1.12"
          
  kafka-kouncil:
      image: consdata/kouncil:1.6
      container_name: kafka-kouncil
      ports:
        - "7071:8080"
      restart: always
      environment:
        - BOOTSTRAPSERVERS=kafka1:19092,kafka2:19093,kafka3:19094
      networks:
        sparknet:
          ipv4_address: 172.28.1.14
      extra_hosts:
        - "kafka1:172.28.1.10"
        - "kafka2:172.28.1.11"
        - "kafka3:172.28.1.12"
volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:
  kafka1-data:
  kafka2-data:
  kafka3-data:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16